### ISSUE TITLE
api/1.2/cdns/health should return the health of mids in addition to edges

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#1224]
api/1.2/cdns/health only returns the health of edge caches. since traffic monitor also monitors the health of mids, mids should be included in the response.

**Comment by mitchell852** [comment]
i'm guessing this is because TR gets info from TM and TR only cares about edges (not mids). sound right @rob05c and @rawlinp

**Comment by rawlinp** [comment]
TR doesn't actually use this route. I think this must be some kind of "TP dashboard" route.

**Comment by ocket8888** [comment]
TR doesn't use `/publish/CrStates`?

**Comment by rawlinp** [comment]
This issue is not about `publish/CrStates`, but TR _does_ use _that_.

**Comment by ocket8888** [comment]
well what Jeremy's saying is that the reason `publish/CrStates` - which is the backend for that TO API endpoint - only reports edge-tier information is because that's all TR cares about, right?

**Comment by rawlinp** [comment]
Yes, TR by design only cares about edge-tier information, which is a good point. TR wouldn't care if it also got MID health information from `publish/CrStates`, but I wouldn't want to add unnecessary data/information to that endpoint just to satisfy this issue. Plus, the idea of a `MID` is actually going away with topologies, so we'd likely want a _new_ endpoint that returns the health of all cache-type servers. However, we don't have a `CACHE` type yet, so I would probably just hold off on this issue altogether IMO.
