### ISSUE TITLE
Manage delivery service static dns entries

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#1301]

**Comment by rawlinp** [comment]
So the TO UI has these routes for CRUDing static DNS entries for a Delivery Service: 
```
	# -- Staticdnsentry
	$r->route('/staticdnsentry/:id/edit')->via('GET')->over( authenticated => 1, not_ldap => 1 )->to( 'StaticDnsEntry#edit', namespace => $namespace );
	$r->post('/staticdnsentry/:dsid/update')->over( authenticated => 1, not_ldap => 1 )->to( 'StaticDnsEntry#update_assignments', namespace => $namespace );
	$r->get('/staticdnsentry/:id/delete')->over( authenticated => 1, not_ldap => 1 )->to( 'StaticDnsEntry#delete', namespace => $namespace );
```
However, the API only has a single endpoint for static DNS entries which just returns all static DNS entries that exist:
```
# -- STATIC DNS ENTRIES
	$r->get("/api/$version/staticdnsentries")->over( authenticated => 1, not_ldap => 1 )->to( 'StaticDnsEntry#index', namespace => $namespace );
```
In order to CRUD static DNS entries for a delivery service using Traffic Portal, we need to add more API endpoints for doing so.

Also, it's a bit weird to have the button to view all static dns entries shown when you are viewing a cachegroup or when viewing the `A` type (for DNS A records). That button should probably exist on the page for viewing all deliveryservices. When viewing a single deliveryservice, you should be able to view all static DNS entries for that delivery service and add/edit/remove entries.

**Comment by mitchell852** [comment]
@dewrich implemented the rest of the api endpoints. see routes.go and search for staticdnsentries

@rivasj is working on plugging those endpoints into TP

**Comment by mitchell852** [comment]
this is all done and merged
