### ISSUE TITLE
Changing operational status of a server queues more than it should

### ISSUE THREAD

**Issue by jhg03a** [apache/trafficcontrol#1665]
In traffic portal, when you change the operational status of a server all DS present on the server are auto-queued for updates.  This means that peer servers within cache ring are being told to update when it makes no difference to them.  It does make sense for child cache rings since you're removing the target server from their parent cache configs.  If you have a wide edge cache with lots of DS on every server this makes it difficult to know which queues are meaningful and which are just noise.

**Comment by mitchell852** [comment]
I don't believe your statement of "all DS present on the server are auto-queued for updates" is technically correct because DSs are not queued for updates. Rather, servers (caches) are queued for updates. 

My understanding is when you change "the operational status of a server" (for example, from REPORTED to ADMIN_DOWN), the system (the API (https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/lib/API/Server.pm#L880) ) auto queues updates for all "child" caches. Child caches are defined as caches that are in a child cache group. 

For example:

- cache group A is the parent of cache group B
- if you change the status of a cache in CG A, then all caches in CG B need to have updates queued.

why is this? because all the caches in CG B (the child cache group) have a file called parent.config which is going to change because as you know, you just changed the status of one of the "parents".

^^ yes, you said this. I was just adding a little more info for others.

Anyhow, yes, if in fact "peer servers" are being queued, this seems like a bug. If I change the status of a cache in CG A, I would not expect the other caches (peers) in CG A to have updates queued....

**Comment by rob05c** [comment]
Labelling `enhancement `because it's always worked this way. Feel free to change to `bug` if you feel strongly about it.

**Comment by mitchell852** [comment]
i'm going to do a check to see if peer caches are queued in this scenario or not. I don't believe they are.

**Comment by mitchell852** [comment]
yeah, 99% sure it doesn't do this @jhg03a . maybe it got fixed at some point. Currently, if a cache group contains caches A, B, C, D and I change the status of cache A, updates are queued for cache A (and it's children) but not for it's peers (B, C, D). Let me know if i can close this.

**Comment by jhg03a** [comment]
We can go ahead and close it out.  It's something that's seemed like it's happened several times, but I don't have a solid reproduce case for it.  If I find one, I can open a new issue or reopen this one.
