### ISSUE TITLE
Traffic Portal: No Use in Table filled

### ISSUE THREAD

**Issue by smalenfant** [apache/trafficcontrol#1693]
When you navigate to the "Types" in Traffic Portal and create a type, there is no "Use in Table" filled. Would be nice to have a list to pick from.

**Comment by mitchell852** [comment]
this is because of the way types were implemented. you can create a type to use for any table. not the best design tbh.

**Comment by mitchell852** [comment]
actually it is now

![image](https://user-images.githubusercontent.com/251272/105089095-eece0380-5a59-11eb-9d8b-9d7ab1a8459e.png)

it's set to `server` because in theory that's the only type of type you can create on the fly with any effect. I.e. You could create an EDGE_FOO type and it would work similar to an EDGE server.
