### ISSUE TITLE
Traffic Portal feature request: the ability to identify if a DS is used as a steering target

### ISSUE THREAD

**Issue by guzzijason** [apache/trafficcontrol#2101]
As a Traffic Portal user, the ability to identify (in the Delivery Service table list and/or in the DS config screen) whether or not this service is a steering target, and if so, also identify the steering config(s) that reference it. Currently, we can only trace the relationship in the opposite direction.

**Comment by mitchell852** [comment]
Not sure if a DS knows that it is a steering target. Sounds like maybe a couple of attributes would need to be added to a DS response along the lines of isSteeringTarget: true|false and steeringSources: [ sources ] or something like that...

**Comment by mitchell852** [comment]
tenancy could make this interesting as a source ds could be outside your tenancy which would give you the impression that a delivery services is not being used as a steering target. just something to think about...

**Comment by mitchell852** [comment]
@jhg03a - you added the "high impact" label. can you explain why? just curious. is this something that is requested frequently?

**Comment by jhg03a** [comment]
While moderately infrequent as an sre, the only workaround is querying todb or writing custom scripts to reconstruct the data.  During outages that awareness can save outage minutes.

It is also an operations safety concern so that there is awareness when updating one steering target there's a decent chance you need to update others you weren't told about. 

And as a self-service consumer, it's an aid to navigate the relationships of DS with one another.
