### ISSUE TITLE
Routes.go file should include type capture groups to enforce route parameter types

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#2243]
for example:

{1.2, http.MethodGet, `asns/{id:[0-9]}$`, api.ReadHandler(asn.GetRefType(), d.DB), auth.PrivLevelReadOnly, Authenticated, nil},

**Comment by mitchell852** [comment]
@DylanVolz @rob05c fyi

**Comment by rob05c** [comment]
What's the goal of this? 

The handler will still get a string, so it still has to cast it, and it should still check the cast succeeds for safety.

The only thing I see this accomplishing, is to allow `asns/{id:[0-9]}` and `asns/{name:[a-z0-9]}` - but what if the name is "42"?

For routes which have the same path for names and IDs, we've been making them try to cast as an int, and assume success means an ID, and failure means a name. We can't do much better for existing routes. And we shouldn't be making any new routes that overlap, because of this problem.

**Comment by DylanVolz** [comment]
The thought was to make the routing less order reliant. While it won't fully remove the need for ordering the routes properly it would make it less brittle.
