### ISSUE TITLE
mid header rewrite location parameter creation is sending to the incorrect CDN

### ISSUE THREAD

**Issue by saoyag001** [apache/trafficcontrol#2460]
Steps to reproduce.
Create a DS with a mid header rewrite in cdn a
check parameters that are created.
hdr_rw_mid_XML-ID.config will show in an incorrect CDN if the Traffic control instance has more than one CDN.

**Comment by rob05c** [comment]
This can't be Go, because DS creation where it was observed isn't in Go yet

**Comment by mitchell852** [comment]
may be related to #2176 as well

**Comment by mitchell852** [comment]
@saoyag001 - need to know what version of TO this bug was observed in.

**Comment by mitchell852** [comment]
also, i think this can happen if a DS from CDN A has a cache assigned to it from CDN B.

**Comment by rob05c** [comment]
This was encountered in the Perl. The endpoint has since been rewritten in Go, which only creates parameters for profiles of servers on the same CDN as the DS https://github.com/apache/trafficcontrol/blob/master/traffic_ops/traffic_ops_golang/deliveryservice/deliveryservicesv13.go#L840

Which is to say, it should be fixed in master.

**Comment by dneuman64** [comment]
I tested this in the latest 3.x release and it is no longer an issue.  Closing.
