### ISSUE TITLE
traffic_ops error null value in column "tenant_id" violates not-null constraint in postinstall

### ISSUE THREAD

**Issue by dbvan** [apache/trafficcontrol#2593]
After run script postinstall traffic_ops error:
```
DBD::Pg::db do failed: ERROR:  null value in column "tenant_id" violates not-null constraint
DETAIL:  Failing row contains (6, admin, null, 1, null, null, SCRYPT:16384:8:1:wo6T3xLKskDlavSuH+cwbsVIG8xuaUEK2iRHEBAWf/0ELYB..., SCRYPT:16384:8:1:wo6T3xLKskDlavSuH+cwbsVIG8xuaUEK2iRHEBAWf/0ELYB..., 2018-07-26 17:11:47.307519+07, null, null, null, f, null, null, null, null, null, null, null, null, null, null). at /opt/traffic_ops/install/bin/_postinstall line 627.
```

**Comment by ocket8888** [comment]
I think this is no longer an issue; firstly because all supported version of ATC use tenancy, but also because the upgrade path to a version _with_ tenancy included running `init_tenancy.sh` - which should eliminate any null values by replacing them with the ID of an "unassigned" Tenant.

If that's wrong, please re-open.
