### ISSUE TITLE
Using bypass fqdn option on a delivery service requires http(s) in the form field

### ISSUE THREAD

**Issue by saoyag001** [apache/trafficcontrol#2768]
This results in bypass error of:
Issue another request to this URL: 'http://http:0/foo'
* getaddrinfo(3) failed for http:0
* Couldn't resolve host 'http'

please remove the http(s) requirement on form field

**Comment by dneuman64** [comment]
+1.  That field is called `http_bypass_fqdn` not `http_bypass_url`.  The field should contain an FQDN and not a URL, so we should NOT have a restriction on `http(s)://`

The current work-around is to edit the field directly in the database.

**Comment by rawlinp** [comment]
This is a problem with the form validation in Traffic Portal, but I just checked traffic_ops_golang and didn't find any validation of `httpBypassFqdn` there either. So, this is really a 2-part fix:
1. Change the pattern validation in TP to match a valid FQDN (rather than a URL)
2. Add API validation in traffic_ops_golang to ensure it's a valid FQDN

**Comment by rawlinp** [comment]
Issue for part 2: #2770
