### ISSUE TITLE
Add Traffic Portal Remembering "Show All Entries" Setting

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#3044]
On every page I visit, I always select the "Show [All]" dropdown. For me at least, the UI is nigh-unusable scrolling, paging, going back to the top, scrolling again.

It would be really convenient if the Portal remembered my setting forever, and automatically selected it and showed all when I went back to the same page.

This should be doable with a cookie or similar.

**Comment by mitchell852** [comment]
It should. It does for me. Maybe this issue is older than when I introduced the behavior to save the state of all tables but it doesn't look like it...

https://github.com/apache/trafficcontrol/blame/master/traffic_portal/app/src/common/service/application/ApplicationService.js#L41

Make sure you have local storage enabled in your browser.

**Comment by ocket8888** [comment]
The issue is definitely older than that, I'd say.
