### ISSUE TITLE
Add cachegroup should not default to deep routing enabled

### ISSUE THREAD

**Issue by dneuman64** [apache/trafficcontrol#3067]
When you add a cachegroup, Traffic Portal has the box selected for deep coverage zone file enabled by default.  Since deep coverage zone is not a default feature, this box should not be checked by default.

![image](https://user-images.githubusercontent.com/5092346/49248548-36efbf00-f3d7-11e8-86df-a76cb69c5432.png)

**Comment by rawlinp** [comment]
It shouldn't hurt anything to have DCZF checked by default. The default behavior is to allow all localization methods for a given cachegroup. Unfortunately, due to "Deep Cachegroups" not being "real" cachegroups (i.e. they're defined only in the DCZF as opposed to in Traffic Ops), you can't really disable deep routing to a deep cachegroup. But by definition a deep cachegroup should always be enabled for deep-routing.

So maybe what we really need to do here is just remove the checkbox for DCZF from TP altogether since it doesn't really apply.

**Comment by mitchell852** [comment]
^^ how does that sound @dneuman64 ?

**Comment by dneuman64** [comment]
Sorry, this was missed a looonnnggg time ago.  I think what Rawlin is proposing is fine.  I just wanted to avoid unnecessary confusion for the user.

**Comment by mitchell852** [comment]
> So maybe what we really need to do here is just remove the checkbox for DCZF from TP altogether since it doesn't really apply.

@rawlinp - Just so I understand correctly. If i remove the `deep coverage zone file` checkbox from TP, what value should be sent on cachegroup create?

DEEP_CZ: true or false?

sounds like true as all cache groups are capable of being deep cz routable....assuming you stick them in the DCZF....

**Comment by rawlinp** [comment]
Under the hood it's an array not a boolean, but I'd say just always include it in the array in the request sent by TP, and remove the deep_cz checkbox altogether.
