### ISSUE TITLE
Traffic Ops Generate KSK endpoint doesn't work if there is no existing KSK

### ISSUE THREAD

**Issue by jhowell-comcast** [apache/trafficcontrol#3153]
When there is no KSK present for a CDN, POSTS to /api/1.4/cdns/{{ cdnNAME }}/dnsseckeys/ksk/generate fail with an internal server error:

```
curl -i -X POST -b mojolicious_cookie_file -d '{"expirationDays":365}' 'https://to.example.net/api/1.4/cdns/exampleCDN/dnsseckeys/ksk/generate'

HTTP/2 500
access-control-allow-credentials: true
access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, Set-Cookie, Cookie
access-control-allow-methods: POST,GET,OPTIONS,PUT,DELETE
access-control-allow-origin: *
content-type: application/json
set-cookie: mojolicious=xxxxxxxxxxxxxxxxxx; Path=/; HttpOnly
whole-content-sha512: xxxxxxxxxxxxxx
x-server-name: traffic_ops_golang/
content-length: 61
date: Thu, 20 Dec 2018 21:06:13 GMT

{"alerts":[{"text":"Internal Server Error","level":"error"}]}
```

**Comment by rob05c** [comment]
Going over the Perl again, I'm not sure if this works in Perl or not. The Perl tries to get the old keys, and references them and uses them everywhere. I'm not enough of a Perl Wizard to know if it's going to fail if they don't exist, or if it will just set all the variables to undefined all the way down.

Either way, re-reading the Go, it looks like it won't be too difficult to make Go generate, even if no old keys exist, and just not set an "expired" key.

But, the Perl was UI, it had no API endpoint. Since the API is new in Go, I'm changing this to `enhancement`.

But, I agree with it, and we should do it, and I don't think it's difficult.
