### ISSUE TITLE
Remove Deprecated Traffic Ops Client Functions

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#3344]
A number of TO client funcs have been deprecated since 3.0, and should be removed from master. 

They can be found by searching for `// Deprecated`, e.g. https://github.com/apache/trafficcontrol/blob/b8cc6076a4b004894f693d5998b7974876274b89/traffic_ops/client/deliveryservice.go#L27

**Comment by Daisykh** [comment]
Taking this one on!

**Comment by rawlinp** [comment]
Here's a pro tip for the deprecated client functions stuff: if it's deprecated in the 3.0.x branch (https://github.com/apache/trafficcontrol/tree/3.0.x/traffic_ops/client) then it should be fair game to remove (since master is currently pegged for 4.0 I believe). I _think_ most of those methods that are currently deprecated were deprecated in 3.0, but there are some that might've been deprecated _after_ that release was cut, meaning they shouldn't be removed until 4.0 is cut. Generally we believe things should be in the "deprecated" state for one major release before removal. Also, we might have Golang components (Traffic Monitor, Traffic Stats, Grove, CiaB Enroller) that are currently using those deprecated functions, so those would have to be fixed to use the non-deprecated functions in those cases.
