### ISSUE TITLE
Move Traffic Ops Riak to a Plugin

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#3347]
Traffic Ops Golang `riaksvc` is currently hardcoded. There are a very small number of functions we do on Riak. 

By moving Riak to a plugin, TC users will be able to use any secure database, making it easy to move away from Riak if it doesn't suit their use case. 

It will also allow us to provide multiple "Secure DB" implementations in TC itself. 

It will also allow us to implement a trivial file or memory DB, so users developing and testing TC could run without the additional work of setting up Riak, making developing, debugging, and trying out TC easier.

I suggest implementing the plugin hook, as a hook which runs on initialization, and plugins return a `SecureDB` interface, which implements the necessary functions to load and store keys.

**Comment by rawlinp** [comment]
This has been implemented in TO now as the `TrafficVault` interface. In order to add support for a new backend, all we have to do is implement that interface for it. Currently, we have support for Riak and Postgres, and with Postgres support the need for an in-memory implementation is less, since it is very easy to setup the Postgres TV backend alongside the TO DB.
