### ISSUE TITLE
Mid/Edge header rewrite rules per DS should not need __RETURN__

### ISSUE THREAD

**Issue by traeak** [apache/trafficcontrol#3426]
Traffic portal should be modified so that header rewrite rules support multi line content instead of requiring an operator to replace file new lines with __RETURN__.

**Comment by smalenfant** [comment]
I believe those header rewrites should be in the DS Profiles instead of being in the ATS Profiles. Not sure how we could add easy UI editor for those DS Profiles as currently it's manual. I just don't like the 1-off ATS Profiles modifications header rewrite currently does which requires database manipulation on server assignments.

**Comment by mitchell852** [comment]
@smalenfant - i believe this issue is simply asking that the following DS form fields:

![image](https://user-images.githubusercontent.com/251272/55639918-bf1c1180-5787-11e9-970a-efca26f2ae67.png)

be converted to a textarea that will preserve line breaks rather than requiring the user to manually enter `__RETURN__` to indicate a line break. simple fix.

**Comment by mitchell852** [comment]
while i'm at it, i'm going to fix these form fields as well

Traffic Router Additional Response Headers
Traffic Router Additional Response Headers
