### ISSUE TITLE
TO Client: Alerts are not returned even when they exist?

### ISSUE THREAD

**Issue by moltzaum** [apache/trafficcontrol#3447]
I am writing an api test for a PR I submitted: #3445

I have the following code:

```
func TryToDeleteDivision(t *testing.T) {
    division := testData.Divisions[0]
    resp, _, err := TOSession.DeleteDivisionByName(division.Name)

    fmt.Printf("resp: %v\n", resp)
    fmt.Printf("err: %v\n", err)

    if err == nil {
        t.Errorf("should not be able to delete a division prematurely")
        return
    }

    if len(resp.Alerts) == 0 {
        t.Errorf("error occurred while deleting division, but no alerts exist")
        return
    }

    switch resp.Alerts[0].Text {
    case "Resource not found.":
        t.Errorf("division with name %v does not exist", division.Name)
    case "This division is currently used by regions.":
        // expected return message
    default:
        t.Errorf("unexpected alert occurred: %v", resp)
    }
}
```

Below is the result. You can see that the error clearly returns the alert message I'm looking for, but when an error occurs the client doesn't return the alerts. At first glance this is confusing. Is there a particular reason this is done? I believe there is a go convention that says a returned error implies the first value is nil, but I don't think that makes sense in this case.

I can write this particular test differently, but maybe this makes sense to change?

```
resp: {[]}
err: 400 Bad Request[400] - Error requesting Traffic Ops https://localhost:6443/api/1.3/divisions/name/division1 {"alerts":[{"level":"error","text":"This division is currently used by regions."}]}
--- FAIL: TestDivisions (4.38s)
	divisions_test.go:47: error occurred while deleting division, but no alerts exist
FAIL
```

**Comment by mitchell852** [comment]
maybe all of our current TO client consumers (Traffic Monitor, TO API test framework, Traffic Stats, Grove) don't really care about the "alerts" as they are really just text messages with an indicator of severity (error, warning, info, success) so the alerts node was never necessary for the client consumers hence it was never added to the TO client? however, since the TO client is a wrapper around the TO api, i think it makes sense to include `alerts`. imo this looks like tech debt.

however, it might be brittle to make a test that checks the verbiage of the alert....maybe checking the severity of the alert would be better? your call.

**Comment by moltzaum** [comment]
I agree that checking the exact message may be brittle, it demonstrates what I want to do better than looking at a severity level. Perhaps I can make a get call and determine the id doesn't exist because the returned array is empty, but that doesn't seem like the best solution.

For my specific case, simply returning the error code would suffice, and some client functions actually do this (eg. everything in `roles.go` as well as `UpdateStaticDNSEntryByID`. In general I think updating functions to return status codes would be better, but I'm still confused why we return alerts, when we only do so for a "success" alert.

**Comment by rawlinp** [comment]
Yeah I think I would agree this is just tech debt. The TO Go client went with a simple interface that doesn't return much _typed_ information about the request (e.g. status code) and mostly just answers the question "did my request work (i.e. was the status code 200)?". A lot of the client methods don't even fully unmarshal the response body for 200s (e.g. `CreateDivision()` returning just `tc.Alerts` instead of something like `tc.DivisionDetailResponse` which would contain alerts _and_ the response).

IMO all the client methods should take nullable structs as input and return nullable structs in the output, and the response should be fully unmarshalled into structs that contain the full response body (i.e. not just `tc.Alerts`). The client methods should also return the response code.

**Comment by moltzaum** [comment]
Also, we have statements like this:
```
    remoteDivision.Name = firstDivision.Name
    alert, _, err = TOSession.UpdateDivisionByID(remoteDivision.ID, remoteDivision)
    if err != nil {
        t.Errorf("cannot UPDATE Division by id: %v - %v\n", err, alert)
    }
```
But `err`, and `alert` are mutually-exclusive, so if an error were to be returned, the alerts would be empty. I think this is a pretty common case.
