### ISSUE TITLE
Delivery Service to Cache Assignment Groups

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#3557]
## Background
Edge caches can currently be assigned to delivery services in three ways:
- By Server Profile
- By Cache Group
- By Individual Cache

The mids of the assigned edges are chosen based only on the parent and secondary_parent cachegroup settings. 

## Problem to Solve
Create a more flexible method of assigning mid/edge caches to delivery services. This allows users to solve the following problems:
- Dedicating a subset of caches to particular content providers/CDN services
- Dedicating a subset of caches to particular content types (i.e. PDL or HTTPS content)
- Specifying exactly which mid-caches are used for a particular delivery service.

The existing "assign by profile" is not sufficient because servers can only be in a single Profile. This proposal introduces a new Cache Assignment Group, of which a server can be in more than one. Also, there is no existing way to influence the selection of mid-caches on a DS-by-DS basis. 

Will followup with a proposal to the dev list. Also will probably create a Project to track the multiple PRs that will be needed.

**Comment by rawlinp** [comment]
I'm looking forward to seeing more about this one. I haven't been able to start on the Flexible Cachegroups/Topologies idea yet, so I'll try to keep an eye on this effort.

Basically, we want to be able to not only form groups out of overlapping subsets of caches but also stack them up and compose them into N-tier Topologies that delivery services are then assigned to.

As part of this, we also want to try to do away with the legacy deliveryservice_server assignments, so for a period of time we would need to support both deliveryservice_server-based assignments _and_ topology-based assignments until we can remove deliveryservice_server assignments altogether. Right now those assignments scale badly in the CRConfig due to requiring DS*C number of entries (deliveryservices times caches).

**Comment by limited** [comment]
This feature is a little less flexible than your goal because we keep the 1/2 tier topology and treat edges and mids as their currently assigned roles. 

Once complete, we could extend this feature to get your n-tier hierarchies by adding parent/child relationships between these groups. This introduces a few new validation challenges we don't have today:
 - Ensuring that delivery services are never assigned to the same cache as both an edge and a mid 
 - Or more generally, ensuring there are no cycles in the topology graph

In this first phase I was planning to keep the assignments as "per-cache" in the CRConfig to avoid changes to TR. We could certainly optimize that back to publishing the group names and the group assignments in the future or when we need the performance.

**Comment by mitchell852** [comment]
> Edge caches can currently be assigned to delivery services in three ways:

> By Server Profile

which api is used to assign all the caches of a certain profile to a ds? I guess i wasn't aware of that functionality.

> By Cache Group

```{1.1, http.MethodPost, `cachegroups/{id}/deliveryservices/?$`, cachegroup.DSPostHandler, auth.PrivLevelOperations, Authenticated, nil},```

> By Individual Cache

```
{1.1, http.MethodPost, `deliveryserviceserver$`, dsserver.GetReplaceHandler, auth.PrivLevelOperations, Authenticated, nil},
{1.1, http.MethodPost, `deliveryservices/{xml_id}/servers$`, dsserver.GetCreateHandler, auth.PrivLevelOperations, Authenticated, nil},
```

**Comment by limited** [comment]
I'm not sure theres a specific API for it, but in the old TO GUI you can click a checkbox for a server profile and it will select all servers in that profile.

**Comment by rawlinp** [comment]
Closing as this functionality is provided by Topologies now.
