### ISSUE TITLE
Error on password reset in Traffic Portal

### ISSUE THREAD

**Issue by madumasvl** [apache/trafficcontrol#3582]
The password reset feature in Traffic Portal returns the following error: 500: Internal Server Error

It does an initial check if will correctly report if the email is not registered, but it doesn't do the reset itself as the previous password remains valid.

Sorry, I don't have access to logs.

**Comment by mitchell852** [comment]
This is the api endpoint that is called when a password reset is requested in Traffic Portal:

https://github.com/apache/trafficcontrol/blob/master/traffic_ops/app/lib/TrafficOpsRoutes.pm#L867

which calls

https://github.com/apache/trafficcontrol/blob/master/traffic_ops/app/lib/API/User.pm#L358

Password reset creates a token and attaches it to the user (if the user email exists) and sends an email with a link to the user's email. By following the link in the email that has the token attached as a query parameter, the user can login to TP via the link and reset their password to what they want.

my guess is you are getting a 500 because you don't have email configured properly.

**Comment by mitchell852** [comment]
If this is determined not to be a bug but rather a set up issue, this issue should be closed.

**Comment by mitchell852** [comment]
closing. please reopen if still having this issue after setting up email in traffic ops.
