### ISSUE TITLE
CDN in a box documentation needs some updating

### ISSUE THREAD

**Issue by dangogh** [apache/trafficcontrol#3592]
The cdn-in-a-box documentation (https://github.com/apache/trafficcontrol/blob/master/docs/source/admin/quick_howto/ciab.rst) is missing some things that were added fairly recently,  including (but not limited to):
- use of `docker-compose.exposeports.yml` (should be mentioned with the first `docker-compose ... up`)
- optional containers: vnc, vpn, grafana, socksproxy, ...

**Comment by zrhoffman** [comment]
`docker-compose.exposeports.yml` was documented more in #3889. The VNC, VPN, Grafana, and Socks Proxy services look adequately-documented to me (though we may consider increasing the `toctree` max depth in the future so that those sections show up in the table of contents.

This issue looks closable to me

**Comment by ocket8888** [comment]
Fixed in #3889.
