### ISSUE TITLE
TO API test failure with atsconfig_test.go

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#3673]
`--- FAIL: TestATSConfigs (14.11s) atsconfig_test.go:50: Getting server by name 'atlanta-edge-01' config list: 400 Bad Request[400] - Error requesting Traffic Ops https://localhost:8443/api/1.4/servers/atlanta-edge-01/configfiles/ats {"alerts":[{"text":"getting integer parameters: parameter 'id' not an integer","level":"error"}]}`

This appears to be related to #3516

**Comment by ocket8888** [comment]
Problem is [here](https://github.com/apache/trafficcontrol/blob/master/traffic_ops/traffic_ops_golang/ats/meta.go#L41); endpoint only allows servers to be indexed by their integral, unique identifier. This would also make ORT unable to function, since it doesn't know the host server's integral, unique identifier at runtime.

**Comment by Shihta** [comment]
tested with PR #3678, seems this is fixed
my test steps:
1. Start CIAB
2. `docker-compose -f docker-compose.yml -f docker-compose.traffic-ops-test.yml up -d`
3. check the result of `../../junit/golang.test.toapi.xml`
