### ISSUE TITLE
CIAB: only works with one deliveryservice

### ISSUE THREAD

**Issue by dangogh** [apache/trafficcontrol#3697]
adding another deliveryservice by creating a new file in `traffic_ops_data/deliveryservices/020-dns1.json:

```
{
    "xmlId": "dns1",
    "displayName": "DNS1",
    "tenant": "root",
    "protocol": 2,
    "orgServerFqdn": "http://origin.infra.ciab.test",
    "cdnName": "$CDN_NAME",
...
```

I get the following message in the `trafficops` logs:
```
return
trafficops_1       | ++ curl -k -LfsS --cookie /tmp/tmp.yffSZJpgz2 -X GET 'https://trafficops.infra.ciab.test:443/api/1.4/deliveryservices/xmlId/demo1
trafficops_1       | dns1/sslkeys?decode=true'
trafficops_1       | curl: (3) Illegal characters found in URL
```

This should be handled appropriately....,

**Comment by Shihta** [comment]
Can you share the complete `traffic_ops_data/deliveryservices/020-dns1.json`?

**Comment by dangogh** [comment]
accidentally deleted it,  but recreated it here... 
```
{
    "xmlId": "dns1",
    "displayName": "dns1",
    "tenant": "root",
    "protocol": 2,
    "orgServerFqdn": "http://origin.infra.ciab.test",
    "cdnName": "$CDN_NAME",
    "type": "DNS",
    "active": true,
    "dscp": 0,
    "geoLimit": 0,
    "geoProvider": 0,
    "initialDispersion": 1,
    "ipv6RoutingEnabled": true,
    "logsEnabled": true,
    "longDesc": "Apachecon North America 2018",
    "multiSiteOrigin": false,
    "missLat": 42.0,
    "missLong": -88.0,
    "qstringIgnore": 0,
    "rangeRequestHandling": 0,
    "regionalGeoBlocking": false,
    "routingName": "dns",
    "anonymousBlockingEnabled": false,
    "signingAlgorithm": null
}
```

**Comment by Shihta** [comment]
In the latest commit (594839f596b1b3a88839e4fb68a56cfbce926478), it is blocked in [line 90](https://github.com/apache/trafficcontrol/blob/master/infrastructure/cdn-in-a-box/traffic_ops/run-go.sh#L90):

that's because there are more than 1 deliveryservices in the variable `ds_name` (demo1 and dns1, in the [line 70](https://github.com/apache/trafficcontrol/blob/master/infrastructure/cdn-in-a-box/traffic_ops/run-go.sh#L78))

since CIAB generates 3 ssl keys so we can add **DNS** as the `demo2`
that means it still need some hard coding, it's hard to make it very flexible

do you still want to add **DNS** as the second deliveryservices?

**Comment by dangogh** [comment]
I don't care what it's called -- just wanted to get a dns service as the 2nd example.  Needs a lot more work to make it flexible...
