### ISSUE TITLE
Incorrect change log entries are being created when editing a delivery service

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#3765]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Editing a delivery service seems to create unnecessary change log entries:

![image](https://user-images.githubusercontent.com/251272/62235878-1bd0b700-b38b-11e9-8a13-1a4b6dd50077.png)

In this case, I simply edited the `long description` of a delivery service but it appears that the consistent hash query parameters and the origin were also updated. Only the 4th change log entry should have been created as i never touched the consistent hash query parameters or the origin.

## Expected / new behavior:

Delivery service change log entries should not reflect changes that did not occur.

## Minimal reproduction of the problem with instructions:

Open a delivery service in TP and edit a delivery service field and inspect the change log entries that were created.

**Comment by rawlinp** [comment]
I think this is just because those things are happening "under the hood" when you update a deliveryservice -- some updates are really a delete+recreate involving tables other than the deliveryservice table (like origin). W.R.T the origin log, updating a delivery service means taking the `orgServerFqdn` field and using that to update its corresponding primary origin (even if the _new_ orgServerFqdn is the same as the _original_). If you were to update the deliveryservice by removing its `orgServerFqdn` (which isn't really doable from TP but is via the API), you would see an audit log like "Deleted primary origin for delivery service: foo" because that update would actually delete its corresponding `origin` resource.

**Comment by mitchell852** [comment]
> I think this is just because those things are happening "under the hood" when you update a deliveryservice

yeah, i figured that's what it was doing so maybe rather than calling this a bug, i should call it an improvement? it's just misleading, that's all and i wanted to capture it before i forgot about it.

**Comment by srijeet0406** [comment]
This has been fixed in https://github.com/apache/trafficcontrol/pull/5410
