### ISSUE TITLE
Rewrite /profiles/name/{{name}}/copy/{{fromName}} to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3813]
## I'm submitting an ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/profiles/name/{{name}}/copy/{{fromName}}` is handled by Perl

## Expected / new behavior:
`/profiles/name/{{name}}/copy/{{fromName}}` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [ ] `POST`

## Minimal reproduction of the problem with instructions:
N/A

**Comment by mitchell852** [comment]
i think this should be deprecated (not rewritten to Go and a deprecation notice added to the response) because....weird...

also, if your intent is to clone a profile, you can do that with import/export i believe.

**Comment by rawlinp** [comment]
I believe TP uses this endpoint for cloning profiles. I think ops probably uses this one quite a bit, so I'm unsure about deprecating it. It's one of those things that could be done using the other APIs, but this acts like a kind of "bulk create" API instead of just creating a new profile with one call, creating all the parameters with individual calls, and associating the parameters to the profile with individual calls.
