### ISSUE TITLE
Rewrite /api_capabilities to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3823]
## I'm submitting an ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/api_capabilities` is handled by Perl

## Expected / new behavior:
`/api_capabilities` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [ ] `GET`
- [ ] `POST`

## Minimal reproduction of the problem with instructions:
N/A

**Comment by mhoppa** [comment]
We should only rewrite the GET and deprecate the POST on this rewrite. As any create/update/delete of api capabilities should be done through db migration and not be dynamic

**Comment by rob05c** [comment]
>We should only rewrite the GET and deprecate the POST on this rewrite. As any create/update/delete of api capabilities should be done through db migration and not be dynamic

I don't think we should deprecate or remove the ability to create and modify user Capabilities or API Capabilities, because they can be used for new endpoints added by Plugins.

Otherwise, every endpoint anyone adds with a Plugin will have to re-implement the user Capabilities system, to control access.

**Comment by ocket8888** [comment]
That was my initial concern as well, but the thinking is that plug-ins should be provided a way to declare their required user capabilities at start-up. I know that doesn't currently exist, but it's also true that user capabilities don't actually control anything (yet).

**Comment by rob05c** [comment]
>plug-ins should be provided a way to declare their required user capabilities at start-up. 

I'd be +1 on that as well. As long as there's some way to specify the required Capabilities/API Capabilities for Plugins, so we don't have to re-implement the system.

That said, currently, Request hooks don't necessarily handle specific routes. They're called on all Requests, and return whether to continue calling non-plugin routes, via the idiom `if !strings.HasPrefix(d.R.URL.Path, "/foo") { return RequestUnhandled}`. It was done that way to give them more power and flexibility. But, it means there's not an obvious right way to handle their Capabilities. We'd have to figure something out.

**Comment by rawlinp** [comment]
From my perspective I think it makes the most sense to have a plugin "seed" its own capabilities somehow on TO startup, and to not allow updating/deleting/creating capabilities at runtime. It wouldn't make sense to me to have a plugin call the `POST /capabilities` API somehow, or to have an operator `POST /capabilities` manually in order for the plugin to work. Since plugins have direct DB access already, I think they should just `INSERT` the capabilities they provide on startup (if they don't already exist).

At the end of the day though, we won't really know if we have a good solution for plugin capabilities unless someone out there actually implements a plugin that uses it.
