### ISSUE TITLE
Internal Server Error message when create a new role

### ISSUE THREAD

**Issue by dandypham** [apache/trafficcontrol#3891]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When I created a new role, with the 30 Privilege Level, it displayed the danger message "Internal Server Error". The role still created.
## Expected / new behavior:

It should displays "Role created" message instead.

**Comment by ocket8888** [comment]
The issue is a nil dereference causing a runtime panic [in the endpoint's handler](https://github.com/apache/trafficcontrol/blob/master/traffic_ops/traffic_ops_golang/role/roles.go#L140). Occurs when the request body doesn't contain a `capabilities` array.

The `POST` method doesn't appear to be captured in [the docs](https://traffic-control-cdn.readthedocs.io/en/latest/api/roles.html), so seemingly there's no guidance for whether or not the `capabilities` property is meant to be optional. Since the endpoint appears to create the Role even though it returns an error code, my suggestion is to make it truly optional by fixing the `nil` dereference on the server side. In that case, no Traffic Portal changes are necessary.
