### ISSUE TITLE
TP: everytime a ds is updated with consistent hash query params the following change log entries are created

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#4016]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [X] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

everytime a ds is updated with consistent hash query params the following change log entries are created

## Expected / new behavior:

everytime a ds is updated, the change log entry should show only the log corresponding to ds upadate made.
## Minimal reproduction of the problem with instructions:

update the DS display name. 
check the changelog
## Anything else:

<img width="290" alt="Screen Shot 2019-10-23 at 12 29 26 PM" src="https://user-images.githubusercontent.com/26607771/67423055-cfafa000-f590-11e9-8fa0-b872c5480ee5.png">

**Comment by ocket8888** [comment]
> _"... the following change log entries are created"_

What change log entries?

**Comment by lbathina** [comment]
attached screenshot

**Comment by ocket8888** [comment]
Thanks.

Seems to be more of an improvement than a bug; relabeling.

**Comment by mitchell852** [comment]
yeah, every time a ds is updated, the consistent hash query params associated with it are deleted and then recreated (probably because that was easier than comparing old versus new) and i believe a change log entry is created on delete and create of ds consistent hash query params. maybe the simple solution is to remove the change log entry from delete and create of ds consistent hash query params.

imo it's enough to create a change log entry when a ds is updated.

**Comment by srijeet0406** [comment]
Fixed in https://github.com/apache/trafficcontrol/pull/5410
