### ISSUE TITLE
To: INternal server error when server capability associated with Server/ds is deleted

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#4033]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [X] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When a server capability associated with a server is deleted, we get internal server error
## Expected / new behavior:

Should return error `Server capability <name> cannot be deleted when servers are associated to it.` 

## Minimal reproduction of the problem with instructions:

1. create server capability 
2. Associate it to a server 
3. delete the server capability created in step1

**Comment by ocket8888** [comment]
Error code should be `409 Conflict` IMO.

**Comment by lbathina** [comment]
same applies to deleting a server capability associated to a delivery service

**Comment by mitchell852** [comment]
this is a bug, not an improvement. deleting a server capability that is assigned to a server or a ds should result in a 400 Bad Request (i think this is normal functionality) or a 409 like @ocket8888 suggested if you want to do it better.

**Comment by lbathina** [comment]
this has been validated and approve fixed

**Comment by lbathina** [comment]
also the message displayed for api is partially correct {"alerts":[{"text":"cannot delete server_capability because it is being used by a server_server_capability","level":"error"}]}
it could be server_server_capability or required capability - can this be updated to user friendly message without exposing db tables?

**Comment by mitchell852** [comment]
https://github.com/apache/trafficcontrol/blob/master/traffic_portal/app/src/common/api/ServerCapabilityService.js#L65

^^ @mhoppa do you want to take this and just change that to false to make sure error message displays? also not sure if you can change error message to "cannot delete server capability because it is being used by a server or required by a delivery service"

**Comment by mhoppa** [comment]
Sure! I can do the first and take a look at the second

**Comment by mhoppa** [comment]
The actual error message comes from a generic interface meaning it effects numerous endpoints and should be handled separately.

**Comment by mitchell852** [comment]
> The actual error message comes from a generic interface meaning it effects numerous endpoints and should be handled separately.

that's what i figured. it's a pretty bad error message but not sure it is blocking this bug from being closed. what do you think @lbathina ? imo however, maybe we need a new issue to address these poor, unfriendly error messages. maybe with the info that @mhoppa has, he can create that issue with the necessary info and we can mark it as tech debt and/or improvement or maybe even api 2.x.

**Comment by mitchell852** [comment]
#4073 closed this issue when it was merged. opening back up so @lbathina can take care of closing it.

**Comment by lbathina** [comment]
https://github.com/apache/trafficcontrol/issues/4076 - related issue for tp

**Comment by lbathina** [comment]
this is fixed. the message displayed 
when the server capability is associated to server only -  the message is displayed correctly - `cannot delete server_capability because it is being used by a server_server_capability`
when the server capability is associated with DS only - the message is displayed correctly. `cannot delete server_capability because it is being used by a deliveryservices_required_capability`
When the server capability is associated with both server and DS - the message is displayed incorrect - `cannot delete server_capability because it is being used by a server_server_capability
` it should be `cannot delete server_capability because it is being used by a server_server_capability and deliveryservices_required_capability`

**Comment by ocket8888** [comment]
It likely doesn't check both and that error message isn't strictly wrong. It's just not as correct as it could be.

**Comment by mitchell852** [comment]
looks lie this bug has been fixed. however, the error message is less than ideal and that is because of the nature of the shared handlers used to implement these apis.

![image](https://user-images.githubusercontent.com/251272/70174061-6d6ab480-1691-11ea-9e2a-2519e305c98a.png)

I'd like to close this issue as fixed and open another one to address the poor nature of error messages at a global level.

**Comment by lbathina** [comment]
As indicated earlier, the internal server error has been fixed long ago. 
However, the error message displayed is incorrect - when the SC is associated to both DS and Server. 
`cannot delete server_capability because it is being used by a server_server_capability` message isn't correct

This issue can be closed for internal server error is fixed. However we need to ensure that the issue mentioned above is tracked if not in this ticket.

**Comment by mitchell852** [comment]
my guess is it's hitting one error at a time.

so if the server capability is assigned to a server AND a ds, then the first error message is:

`cannot delete server_capability because it is being used by a server_server_capability`

and then once you remove the sc from the server, is the next error message something like this?

``cannot delete server_capability because it is being used by a deliveryservice_server_capability``

**Comment by lbathina** [comment]
yep. I will raise a new issue for that.
