### ISSUE TITLE
Making a GET and PUT request to users/register returns wrong response

### ISSUE THREAD

**Issue by ZugNZwang** [apache/trafficcontrol#4212]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

The `users/register` endpoint should only allow for `POST` requests. However, when making a `GET` request an incorrect error response is returned:
```
HTTP/1.1 400 Bad Request
{
    "alerts": [
        {
            "text": "id cannot parse to integer",
            "level": "error"
        }
    ]
}
```
And when making a `PUT` request this incorrect response is returned:
```
HTTP/1.1 400 Bad Request
{
    "alerts": [
        {
            "text": "'fullName' cannot be blank, 'username' cannot be blank",
            "level": "error"
        }
    ]
}
```

## Expected / new behavior:

Should return
```
HTTP/1.1 405 Method Not Allowed
{
    "alerts": [
        {
            "level": "error",
            "text": "Resource not found."
        }
    ]
}
```

**Comment by ocket8888** [comment]
This is because when you do `GET /users/register` it thinks you're asking for a user with the ID "register". So that's actually an appropriate error message, because "register" is not a valid ID. When you do `PUT /users/register` it thinks you're trying to edit a user with the ID "register". Ideally I think that'd return the same error message, but the one it gave you isn't wrong either - those request body parameters are required for that endpoint.

Also, no other endpoint supports `405` - that's an API-wide problem that arises from the same root cause of your confusion on this issue: An endpoint is defined as a combination of request method and path. They should actually be defined by paths and those paths should have supported methods. But that's not the world in which we live.
