### ISSUE TITLE
Making a PUT or DELETE request to cdns/health returns wrong response

### ISSUE THREAD

**Issue by ZugNZwang** [apache/trafficcontrol#4213]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

The `cdns/health` endpoint should only allow for `GET` requests. However, when making a `PUT` request an incorrect error response is returned:
```
HTTP/1.1 400 Bad Request
{
    "alerts": [
        {
            "text": "EOF",
            "level": "error"
        }
    ]
}
```
This is because it is expecting something in the body. But the method should not be allowed at all.
And when making a `DELETE` request this incorrect response is returned:
```
HTTP/1.1 400 Bad Request
{
    "alerts": [
        {
            "text": "failed to parse key: id",
            "level": "error"
        }
    ]
}
```

## Expected / new behavior:

Should return:
```
HTTP/1.1 405 Method Not Allowed
{
    "alerts": [
        {
            "level": "error",
            "text": "Resource not found."
        }
    ]
}
```

**Comment by ocket8888** [comment]
As in #4212 this is because you're actually accessing other endpoints like `DELETE /cdns/{{ID}}` and `PUT /cdns/{{ID}}`

**Comment by ZugNZwang** [comment]
The request is being made to `cdns/health` though. Shouldn't that endpoint deny any methods that are not used?

**Comment by ocket8888** [comment]
It should but it can't. Like I said in #4212 the problem is that our API is designed such that endpoints are defined by a request method **and** a request path, so if you do `PUT /cdns/anythingelse` you will never encounter `cdns/health`, because `PUT` isn't part of that endpoint's definition. That ought not to matter, but unfortunately it does.

I'm not saying this isn't an issue, just that it's a different issue than "Making a {{METHOD}} request to {{endpoint}} returns wrong response" because that's a systemic problem with the design. "Solving" that means embracing undefined behavior on collisions between identifiers and endpoint paths, or redesigning the API so that endpoints are totally represented by path and as a separate concept support a set of request methods. The latter option is (I think?) already captured in an issue - but if it isn't feel free to open one (or just edit this and I'll reopen it if you prefer). It's just gotta be more broad because otherwise we'll have dozens of these all related to the same underlying issue.

**Comment by rob05c** [comment]
Can we not just add a `{1.1, http.MethodDelete, `cdns/health/?(\.json)?$`, notImplementedHandler, auth.PrivLevelReadOnly, Authenticated, nil, 1085281135, perlBypass},` route?

**Comment by ocket8888** [comment]
Yes and no. That won't give back the `405 Method Not Allowed` request he was talking about, but it would sort of fix this specific bug. The broader problem, though, is that the same issue exists for /users/register, /servers/totals, etc. etc. One solution would be to add extra handlers for all those, but FWIW that's been shot down in one of my PRs before so dunno how much support that would get. Plus IMO getting rid of path parameters is a more elegant solution.
