### ISSUE TITLE
Email response errors from users/register and user/reset_password

### ISSUE THREAD

**Issue by ZugNZwang** [apache/trafficcontrol#4216]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When making a `POST` request to `users/register` or a `POST` request to `users/reset_password`, will send an email. There are errors in the email subject:
 `A new account has been created for you on the ... - groups['traffic_ops'][0].split('.')[1:2] Portal. In the ... - groups['traffic_ops'][0].split('.')[1:2] Portal, you'll find a dashboard that provides access to all of your Delivery Services.`
and email message:
`... - groups[&#39;traffic_ops&#39;][0].split(&#39;.&#39;)[1:2] New User Registration`

**Comment by ocket8888** [comment]
Can you show me the request bodies you used?

**Comment by ocket8888** [comment]
After digging into the actual environment used, it was determined that the problem was with the configuration itself and not this endpoint. The `tm.instance_name` parameter on the `global` ConfigFile had a value literally containing `groups['traffic_ops'][0].split('.')[1:2]`. So not a real TO bug, just some automation gone slightly awry.
