### ISSUE TITLE
Message does not display properly when user assign Servers to the Delivery Service on the first time

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#4252]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Go to Services -> Delivery Services and choose any DS that is not Steering. Choose More -> Manage Servers then assigned new Servers to the Delivery Service. The message "server assignments complete" will only display for like 1 second then it will disappear. 
<img width="1674" alt="Screen Shot 2020-01-02 at 2 19 06 PM" src="https://user-images.githubusercontent.com/21675397/71693906-df0a5100-2d6a-11ea-9beb-10466a670381.png">

But if user stay on that page and keep assigning servers to the Delivery Services. The message will display properly. 
<img width="1669" alt="Screen Shot 2020-01-02 at 2 20 01 PM" src="https://user-images.githubusercontent.com/21675397/71693960-0103d380-2d6b-11ea-8712-930cbe64549f.png">
If user want to see the bug again, user have to go back out to the Delivery Services page and choose Manage Servers again.
## Expected / new behavior:

When user add new Servers to the Delivery Services, the message will display properly.

**Comment by ZugNZwang** [comment]
So when clicking on a **Delivery Service** and it will go to this route: `/#!/delivery-services/124?type=ANY_MAP`

Then click the **More** drop down menu, click on **Manage Servers**, and it will go to: `/#!/delivery-services/124/servers?type=ANY_MAP`

When clicking on the **Link Button**, selecting servers, and clicking **Submit**. The Servers Table will close. It will briefly display the alert message: `server assignements complete`
And it will end up at this route: `/#!/delivery-services/124/servers`

I noticed this route no longer has the type query parameter. And that also this issue only occurs when performing these actions in order, if the user is already on the page you don't get this issue.

Seems like this issue exists because it is navigating to a different route right after the server assignments.

**Comment by mitchell852** [comment]
> Seems like this issue exists because it is navigating to a different route right after the server assignments.

that's exactly the problem. great observation.
