### ISSUE TITLE
getting newer versions to appear on pkg.go.dev

### ISSUE THREAD

**Issue by jba** [apache/trafficcontrol#4380]
This is the pkg.go.dev team responding to the feedback left today, which reads:

> Note the "Published: Jun 30, 2015". Our master branch gets updates nearly daily, making this page nearly 5 years out-of-date. We also have published releases, the most recent stable release being last October. Not sure which you try to use.

The Go module system recognizes module versions by semantic version tags on the repo, as described in the [go command doc](https://golang.org/cmd/go/#hdr-Modules__module_versions__and_more) and [this blog post](https://research.swtch.com/vgo-module). We look at those tags (indirectly, via the [module proxy index](https://index.golang.org)), and we consider the latest one to be the highest (in the semver sense) "release" tag. A release tag is of the form vX.Y.Z. If there is a higher prerelease tag (vX.Y.Z-blahblah) or [pseudo-version](https://golang.org/cmd/go/#hdr-Pseudo_versions), we remember it but don't consider it "latest."

So by our definition, the latest version of your repo is v1.1.3, published June 30, 2015.

If you were to tag your current master v1.1.4, then fetch it through the proxy using `go get`, we would soon update our page.

Hope this helps.

**Comment by ocket8888** [comment]
Well our project neither now is nor ever was a go *module*, nor does consist even in part of go modules. There has been talk of using the go module system, but one of our dependencies has issues with the newer versions of Go that support modules, so we can't at this time. We likely won't change the tag naming scheme until such time that it becomes necessary (that is, when we switch to the Go module system).

**Comment by zrhoffman** [comment]
[`v5.0.0`](https://github.com/apache/trafficcontrol/commits/v5.0.0) now [shows up](https://pkg.go.dev/github.com/apache/trafficcontrol@v5.0.0+incompatible) on pkgs.go.dev, but as `v5.0.0+incompatible`, so [`v1.1.3`](https://pkg.go.dev/github.com/apache/trafficcontrol@v1.1.3) is still listed as the latest version. In order to get `+incompatible` removed, I think we would need to tag `v2.0.0`, `v3.0.0`, and `v4.0.0`.

**Comment by ocket8888** [comment]
I don't think creating new tags would be a big deal - if we really want to keep the practice of naming our releases like `RELEASE-{{VERSION}}` (which I don't *think* is mandated by Apache or anything) then we could totally still do that, just augmenting with more tags.

**Comment by jba** [comment]
> In order to get `+incompatible` removed, I think we would need to tag `v2.0.0`, `v3.0.0`, and `v4.0.0`.

No, you need to have a go.mod file.

See https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning, especially the paragraph beginning "Code written."

**Comment by ocket8888** [comment]
Welp. Looks like this'll need to wait for #5229

**Comment by ocket8888** [comment]
now that #5229 is closed, looks like the next _major_ release will close this (and #5488). I don't think this will make it into 5.1, unfortunately.

**Comment by zrhoffman** [comment]
> That doesn't even really seem like versioning the package at all, it's just releasing a different package with a similar name and something that looks like - but by no means must be - a version number in it. I don't like living in a world where `go mod edit -require github.com/wilk/uuid/v3@1.2` is a sensible command.

There is no such thing as `github.com/wilk/uuid/v3@1.2`. If you include `/v3`, it will only grab version greater than or equal to `v3` and less than `v4`. As @jba says, the idea is that, once you require a module like `github.com/go-acme/lego/v3`, you

* don't need to specify an exact version in order to grab `v3`, and
* can can upgrade to the latest version of that package without importing breaking changes (presumably in `v4` and above).

**Comment by zrhoffman** [comment]
One thing to note is that, although appending `/v6` to the module path would make the new module path importable, the latest Go docs would not replace the `v5.1.3+incompatible` Go docs.

To see this effect on another project, although [Migrate's readme](https://github.com/golang-migrate/migrate#versions) says, for `v3`

> **DO NOT USE** - No longer supported

[The pkg.go.dev documentation for go-migrate](https://pkg.go.dev/github.com/golang-migrate/migrate) shows v3

![Migrate v3 Go docs](https://user-images.githubusercontent.com/11163823/138366303-0527a8a3-6a73-44e4-8e07-a7669af10e67.png)

with `v4` at, as expected, a separate path:
![Migrate v4 Go docs](https://user-images.githubusercontent.com/11163823/138366424-f9dcf8cb-7b7c-4225-9d71-2e912f78ae9e.png)

So, getting the newer version to show up on pkg.go.dev will not keep the older version from showing up on pkg.go.dev by default at the repo's path.

**Comment by ocket8888** [comment]
In the discussion to which jba kindly linked us, a proposal is linked for automating the package path updating associated with major version revs: https://github.com/golang/go/issues/32014. It's not done yet, but could possibly help. I still think 2500 lines of changes for simple version housekeeping on every release is far, far too much, and I'm not so much concerned with using my editor's find/replace function as I am with having to comb through those changes and ensure they were all intentional. Nevertheless, that tool would be an improvement over a manual update, and probably much less error-prone (although documentation e.g. in READMEs and comments would have to be done by hand, still, in all likelihood). Also we'd have cool imports like `github.com/apache/trafficcontrol/traffic_ops/v4-client/v8@v8.2.7` which has a confusing number of embedded versions. Though it may be _literally_ simple to know which version means what, that's still confusing for a human to look at.
