### ISSUE TITLE
User can assign ORG servers from different CDN to Delivery Service

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#4791]
## I'm submitting a ...
- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...
- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
User can assign ORG Servers from CDN1 to Delivery Service with a Topologies in CDN2 by using 2 API `deliveryserviceserver` and `deliveryservices/{{xml_id}}/servers`.

For example: 
First, create a DS in CDN1 and assign it a Topologies. Next, create a  ORG Servers in CDN2. 
Then by using `https://{{TO_BASE_URL}}/api/3.0/deliveryservices/dstestname/servers` 
With payload 
```json
{ "serverNames": [ "servername" ] }
```
or
By using `https://{{TO_BASE_URL}}/api/3.0/deliveryserviceserver`
With payload 
```json
{
	"dsId": number,
	"replace": false,
	"servers": [ number ]
}
```
The Server will assign successully to Delivery Service with 200 OK code.
## Expected / new behavior:

Should return 400 Bad Request.

**Comment by mitchell852** [comment]
I'm kind of surprised https://github.com/apache/trafficcontrol/pull/4754 did not fix this. Technically, I think you can _currently_ assign ANY type of server to a delivery service (edge, mid, org, rascal, ccr, etc) but only 2 types have any impact: EDGE* and ORG (ORG servers are for MSO delivery services). TBH, since the only assignments that have any impact are EDGE* or ORG servers, there should probably be some validation to ensure that other types are never assigned. Therefore, the assignment rules should be:

If ds HAS a topology, server assignments are NOT allowed EXCEPT for ORG servers in the same CDN.
If ds has NO topology, server assignments ARE allowed of EDGE* or ORG type as long as they are in the same CDN.

@rawlinp @ocket8888 ^^ is that how you understand it?

**Comment by ocket8888** [comment]
Topologies contain Cache Groups, which are not bound to CDNs. I think you can assign Cache Groups containing servers from any CDN, but only those servers within the DS's CDN are actually chosen to serve its content.

**Comment by mitchell852** [comment]
> Topologies contain Cache Groups, which are not bound to CDNs. I think you can assign Cache Groups containing servers from any CDN, but only those servers within the DS's CDN are actually chosen to serve its content.

yes, true statement

**Comment by mitchell852** [comment]
so you can't assign ORGs from cdn1 to a delivery service cdn2 @dpham692 ?
