### ISSUE TITLE
Support Queuing Updates by Server Type

### ISSUE THREAD

**Issue by dsouza93** [apache/trafficcontrol#4982]
## I'm submitting a ...

-  new feature / enhancement request

## Traffic Control components affected ...

-  Documentation
-  Traffic Ops
-  Traffic Ops ORT
-  Traffic Portal

## Current behavior:

There has been the need to queue only the edge caches or only the mid caches. Currently, this has to either be done by writing a script to hit the API, or hacky ways like admin_downing mid caches in each cache group to queue updates on edges.

## Expected / new behavior:

I'd like the ability to only queue updates on a specific tier. To expand on this it might be nice to be able to queue based on a profile regex as well.

## Minimal reproduction of the problem with instructions:

N/A

**Comment by mitchell852** [comment]
Maybe we need to consider a new endpoint like:

POST (or PUT) /api/queue_updates with a bunch of supported query params such as:

/api/queue_updates?cdn=
/api/queue_updates?cacheGroup=
/api/queue_updates?server=(hostname? id? both?)
/api/queue_updates?type=
/api/queue_updates?profile=
/api/queue_updates?topology=
/api/queue_updates?deliveryService=(xmlId? id? both?)
/api/queue_updates?physLocation=
/api/queue_updates?serverCapability=
/api/queue_updates?status=

that would give the user lots of options on how they wan to queue updates :)

**Comment by srijeet0406** [comment]
@mitchell852 I can take this one.

**Comment by srijeet0406** [comment]
Talked to @mitchell852 about this, and for this issue, I'll be adding queueing updates by Type only. We can keep adding to that endpoint later as we'd like.

**Comment by dsouza93** [comment]
Queueing updates by type and profile only seems acceptable and more user friendly! Sounds good to me.

**Comment by rawlinp** [comment]
Rather than adding a new endpoint, would it make sense to just add `type` and `profile` query parameters to the existing `/cdns/{id}/queue_update` endpoint? I think most of the time you're queuing within a single CDN, so it might make sense to keep it CDN-specific, but within that CDN you can narrow down by server type and profile.

I would prefer us to move away from having to do targeted queues in the first place -- in general if you queue updates on a server that doesn't actually have updates, it should be a no-op. The problem is that it adds load on Traffic Ops to serve requests from `t3c` when they're not actually needed. However, we are trying to get to a point where Traffic Ops can easily handle the load from thousands of `t3c` instances at a time, so eventually we should be able to just queue entire CDNs at a time and have the change fully propagated in a few minutes rather than an hour.

**Comment by mitchell852** [comment]
> Rather than adding a new endpoint, would it make sense to just add `type` and `profile` query parameters to the existing `/cdns/{id}/queue_update` endpoint? I think most of the time you're queuing within a single CDN, so it might make sense to keep it CDN-specific, but within that CDN you can narrow down by server type and profile.

this makes sense to me
