### ISSUE TITLE
Server page: restore to single click navigate and add "copy cell contents" menu item.

### ISSUE THREAD

**Issue by traeak** [apache/trafficcontrol#5211]
## I'm submitting a ...

-  improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...

-  Traffic Portal

## Current behavior:

Version: 5.0.0 from 2020-10-22
New functionality on the servers page requires a double click to navigate to the specific server instead of a single click that was there before.  First off there's no indication that double click is needed while single click still works on other typical pages.

## New behavior:

In order to restore single click it might work to add a menu item for "copy cell contents" for copy/paste ability.

**Comment by rawlinp** [comment]
+1

**Comment by shamrickus** [comment]
We could detect if the mouse is held down, if so then don't open the server (to allow copying); but, if the mouse is just clicked then it will open the server as usual.

**Comment by rob05c** [comment]
+1 - double-click is very unintuitive to me. I would've never guessed that.

So, I frequently want to select and copy text from the Servers page, e.g. hosts and IPs to put in a terminal or URL bar. I assume that's the problem double-click was trying to solve.

As Steve said, detect hold-downs. Could we make the UI event onmouseup instead of down, and detect if text was selected, and if so not trigger the click/navigate? That seems ideal to me, if it's possible?

If not, we could change the row to not click anything, and add a column of buttons on the right or left, to click to navigate to each server's page.

I'd +1 either of those, over either double-click or the current situation of trying to copy text being extremely painful.

**Comment by mitchell852** [comment]
> So, I frequently want to select and copy text from the Servers page, e.g. hosts and IPs to put in a terminal or URL bar. I assume that's the problem double-click was trying to solve.

yes, that's what double-click was trying to solve and yes, double click not intuitive. will revert and look at better solutions to the copy/paste pain.
