### ISSUE TITLE
Should not let user assign Topology to Delivery Services that already linked with an EDGE Server

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#5258]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Portal

## Current behavior:

TP let user assign Topology to a DS that currently linked with an EDGE Server.
## Expected behavior:

TP should not allow user to assign Topology to a DS that currently linked with an EDGE Server.
## Minimal reproduction of the problem with instructions:

1. Create Delivery Services with no Topologies. Create a an EDGE Server. 
2. Link DS with the EDGE Server.
3. Go back to Delivery Services and update it to have a Topologies. Notice that it success.

**Comment by rawlinp** [comment]
I believe the existing behavior is actually what we want. We would like to keep ds-server assignments in place for existing DSes but just ignore them if the DS is updated to use a topology. Once assigned to a topology, however, we should prevent assigning EDGE caches to a topology-based DS. Although, we _do_ allow assigning topology-based DSes to servers, in order to allow the cloning of DS assignments from server to server.

**Comment by mitchell852** [comment]
> TP let user assign Topology to a DS that currently linked with an EDGE Server.

Yes, this behavior is fine as @rawlinp said.
