### ISSUE TITLE
TM repeatedly logging events for ADMIN_DOWN caches

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#5306]
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Monitor

## Current behavior:
If a cache is `ADMIN_DOWN`, it appears that TM will log an event for the cache every single time it is polled:
```
1605800485.067 host="my-edge", type=EDGE, available=false, msg="Protocol (IPv4) ADMIN_DOWN - available (health) "
1605800487.140 host="my-edge", type=EDGE, available=false, msg="Protocol (IPv6) ADMIN_DOWN - available (health) "
1605800489.045 host="my-edge", type=EDGE, available=false, msg="Protocol (IPv4) ADMIN_DOWN - available (health) "
1605800489.977 host="my-edge", type=EDGE, available=false, msg="Protocol (IPv6) ADMIN_DOWN - available (stat) "
1605800490.857 host="my-edge", type=EDGE, available=false, msg="Protocol (IPv6) ADMIN_DOWN - available (health) "
```

## Expected behavior:
Before 5.0.x, TM would not repeatedly log events for `ADMIN_DOWN` caches every time they were polled. I believe TM should only be logging events for changes in availability, which is how it has always logged events. Since `ADMIN_DOWN` caches are always unavailable for routing, these events should not be logged.

## Minimal reproduction of the problem with instructions:
Set a cache to `ADMIN_DOWN`, snapshot, observe TM event logs.

## Anything else:
This appears to affect version 5.0.x/master, compared to 4.1.x.

**Comment by shamrickus** [comment]
This is because previously the message would only be logged if the new status was different than the previous. It was changed to always log if it's _not_ available. 
5.0
https://github.com/apache/trafficcontrol/blob/6635c686c5694b633291a4a2f00c923031fd6aa1/traffic_monitor/health/cache.go#L325
4.1
https://github.com/apache/trafficcontrol/blob/817a702a9de6169c86e30cd70304af380a8e9dc6/traffic_monitor/health/cache.go#L227

**Comment by rawlinp** [comment]
Ah, I don't think we want to always log if a cache is not available -- only when it changes states.
