### ISSUE TITLE
TO unable to unassign ORG server from delivery services if it's the last assigned

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#5390]
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Ops

## Current behavior:
As of https://github.com/apache/trafficcontrol/pull/5328, TO prohibits unassigning all servers from an active delivery service, including `ORG` servers.

## Expected behavior:
This validation should be limited to server types that begin with `EDGE`, since the validation should be designed to prevent the accidental removal of all `EDGE`-type servers from an active delivery service.

## Minimal reproduction of the problem with instructions:
Create an active delivery service and assign an `ORG` server to it. Try to remove the `ORG` server from the active delivery service.

## Anything else:
Once fixed, [this TODO](https://github.com/apache/trafficcontrol/pull/5350/files#diff-8bed268f92ae2156b9b90850085c66313c485e2700c74d509c6f3a52b60f7bf3R282) should be completed so that the test properly cleans up after itself.

**Comment by srijeet0406** [comment]
Just mentioning this here to avoid any confusion:
Here is how I tested and verified this --

Create a new active DS in TP
Try to assign a server to this DS that is not in the ONLINE/ REPORTED state -> this should fail
Now, try to assign an EDGE that is in ONLINE/ REPORTED state -> this should pass
Try deleting this EDGE server from TP and also from the backend API call -> both these actions should be prevented

Now create a new active DS in TP
Assign an ONLINE/ REPORTED ORG server to this DS from TP -> this should pass
Now, try to unassign this server from TP -> this should be prevented, because TP uses the replace=true mode, and you cannot unassign(or replace) all servers from an active DS
Try to delete this server from the backend call -> this should pass, since this is an ORG server

Note: to make a backend call to the DELETE api, use this endpoint:
DELETE https://<TO HOST:PORT>/api/3.0/deliveryserviceserver/<DS ID>/<SERVER ID>
