### ISSUE TITLE
PUT users/{id} endpoint has incorrect use of COALESCE for field new_user

### ISSUE THREAD

**Issue by rimashah25** [apache/trafficcontrol#5443]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

- Traffic Ops

## Current behavior:

In TP, 
1. Register a user.
2. Click on the new registered user.
3. Update the full name and/or username. TP calls API: PUT users/{id}
4. Check the database and notice the field `new_user` is still set to true.

## Expected behavior:

On above step 4, the field `new_user` should be set to false after an update.

## Minimal reproduction of the problem with instructions:

Reproduce the issue with steps mentioned in the Current behavior.

**Comment by mitchell852** [comment]
yeah, new_user should be set to false _always_ when a user is updated. updating implies that the user is no longer a "new user" :)

**Comment by mitchell852** [comment]
`PUT user/current` needs to set new_user to false as well if it does not already.

**Comment by rimashah25** [comment]
> `PUT user/current` needs to set new_user to false as well if it does not already.

It does set new_user field to `false` without using coalesce attribute

**Comment by ocket8888** [comment]
I think the purpose of the `new_user` field is to cause TP to prompt them to change/set their password on login. The intention is that if that hasn't yet occurred, then the user is still "new". If someone else updates the user object e.g. because they realized the user needs to be in a higher tenant before the user completes registration, then it won't properly prompt then on their first login if you make this change. I think the behavior is currently working as intended, roughly. The only thing is that _any_ update through `user/current` is unsetting that field, when really I think it should only count password updates. But that's just my opinion.

**Comment by mitchell852** [comment]
> I think the purpose of the `new_user` field is to cause TP to prompt them to change/set their password on login. The intention is that if that hasn't yet occurred, then the user is still "new". If someone else updates the user object e.g. because they realized the user needs to be in a higher tenant before the user completes registration, then it won't properly prompt then on their first login if you make this change. I think the behavior is currently working as intended, roughly. The only thing is that _any_ update through `user/current` is unsetting that field, when really I think it should only count password updates. But that's just my opinion.

yep, @ocket8888 is right. newUser only gets set to false via PUT /users/current because when the user is updating their own user, they are no longer "new". a very hacky solution but it was it is...

**Comment by rimashah25** [comment]
Ok.. so closing the issue since it is working as intended.

**Comment by mitchell852** [comment]
the real bug maybe the fact that registration_sent is set to null on PUT /user/id and i have no idea why we'd want that behavior.
