### ISSUE TITLE
Optional ATS pkg build fails

### ISSUE THREAD

**Issue by jhg03a** [apache/trafficcontrol#5621]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  CDN in a Box
-  ATS

## Current behavior:

An error is thrown while building the docker layer for pip while trying to build ATS

## Expected behavior:

An RPM would be produced

## Minimal reproduction of the problem with instructions:

Attempt to use the pkg script to compile ats on a host with no prebuilt docker images, cache, or cache layers.

## Anything else:

```
Step 5/12 : ADD	https://bootstrap.pypa.io/2.7/get-pip.py /

 ---> 76be2c117e8f
Step 6/12 : RUN	python get-pip.py
 ---> Running in e9ab849058ea

Hi there!

The URL you are using to fetch this script has changed, and this one will no
longer work. Please use get-pip.py from the following URL instead:

    https://bootstrap.pypa.io/pip/2.7/get-pip.py

Sorry if this change causes any inconvenience for you!

We don't have a good mechanism to make more gradual changes here, and this
renaming is a part of an effort to make it easier to us to update these
scripts, when there's a pip release. It's also essential for improving how we
handle the `get-pip.py` scripts, when pip drops support for a Python minor
version.

There are no more renames/URL changes planned, and we don't expect that a need
would arise to do this again in the near future.

Thanks for understanding!

- Pradyun, on behalf of the volunteers who maintain pip.

ERROR: Service 'ats_build' failed to build : The command '/bin/sh -c python get-pip.py' returned a non-zero code: 1
Failed to build ats_build.
```

**Comment by ocket8888** [comment]
> pip/2.7

ATC doesn't officially support Python2 and I would love for that to trickle down everywhere Python scripts are used

that's important because for any version after 3.4.0 you can actually just do `python -m ensurepip` to download the supporting `pip` package. On some systems (Debian/Ubuntu for sure) that's disabled, but on others - possibly this one - that will handle everything for you without the extra step of downloading a bootstrap script.
