### ISSUE TITLE
MSO Topologies Breaks "Last Header Rewrite Rules"

### ISSUE THREAD

**Issue by dsouza93** [apache/trafficcontrol#5638]
## I'm submitting a ...

-  bug report
## Traffic Control components affected ...

-  Traffic Ops
-  Traffic Ops ORT

## Current behavior:

If you are using an MSO like topology, the "Last Header Rewrite" rules do not get applied in the remap config. By MSO like topology I mean one in which origins are used as the root of the topology. 
I am assuming this is because code in ORT that determines what is the most outer most tier of the CDN is incorrectly assuming that the origin is the outmost tier, but this is just a guess. 

You cannot get around this bug by placing the "Last Header Rewrite" as the "Inner Header Rewrite". I tried this with no success. 

## Expected behavior:

With MSO like topologies, the "Last Header Rewrite" should be applied on the final tier of the CDN.

## Minimal reproduction of the problem with instructions:

Create an MSO topology (one with a cache group made up of ORG servers) . Apply it to an MSO delivery service that has said ORG servers assigned. Set a "Last Header Rewrite Rule" on that delivery service. Run ORT and notice that the hdr_rw file gets placed on disk, but does not get configured in the remap.config.

**Comment by rob05c** [comment]
This is fixed by https://github.com/apache/trafficcontrol/pull/5642 (and its dependent PRs).
I'm not sure exactly the root or where it was fixed. But those changesets fix a number of related things, including minor fallback and header rewrite injection.

I specifically tested this with #5642, and the MSO hdr_rw_last_ was properly injected on the last cache tier, both the remap.config line directive and the hdr_rw_last_ file were created correctly.

**Comment by rob05c** [comment]
#5642 is merged, which fixes this. Closing. Reopen or make a new case if it shows up again.
