### ISSUE TITLE
Traffic Portal Invalidate Content page: warning about origin needing to support 304s

### ISSUE THREAD

**Issue by traeak** [apache/trafficcontrol#5698]
## I'm submitting a ...

-  improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...

-  Traffic Portal

## Current behavior:

Recently we issued a large scale invalidation request against one of our delivery services.  Unfortunately we didn't realize that the origin was not configured to handle If-Modified-Since or If-None-Match headers and always sent back 200s instead of 304s.  This resulted in a storm of requests going to the origin, and a new mini storm starting every time an edge cache ATS was restarted.

Perhaps some message or some documentation should be added to ensure that whoever uses Invalidations realizes that they are designed to be used with origins that properly handle IMS requests.

**Comment by mitchell852** [comment]
Seems easy enough to create a warning in both of these places in TP:

https://tp.domain.tld/#!/jobs/new
https://tp.domain.tld/#!/delivery-services/{{id}}/jobs?type={{ds_type}}

something along the lines of "Delivery service origin must support IMS in order to safely invalidate content"

Also, that should be added to the documentation: 

https://traffic-control-cdn.readthedocs.io/en/latest/admin/quick_howto/content_invalidation.html
https://traffic-control-cdn.readthedocs.io/en/latest/admin/traffic_portal/usingtrafficportal.html

and anywhere else in the documentation that discusses content invalidation.

**Comment by TaylorCFrey** [comment]
Throw this one on my docket!
