### ISSUE TITLE
Login failure loop in v5.1.0 go v3-client

### ISSUE THREAD

**Issue by guzzijason** [apache/trafficcontrol#5739]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Control Client
-  Traffic Ops

## Current behavior:
When building go client applications with the TC v5.1.0 v3-client library, we have observed that a login failure (such as resulting from passing incorrect login credentials) results in a looping condition, where a steady stream of login attempts are made against TO API.

## Expected behavior:
When invalid login credentials are used, the login attempt should fail immediately, without a apparent retry loop.

## Minimal reproduction of the problem with instructions:
Build a client app using `github.com/apache/trafficcontrol v5.1.0+incompatible`.
Pass invalid login credentials to that app.

## Anything else:
Confirmed that building with `github.com/apache/trafficcontrol v5.0.0+incompatible` does not reproduce the problem.

**Comment by rawlinp** [comment]
For whoever fixes this:
`request()` is calling `login()` if the 1st attempt returned 401. `login()` eventually makes its way back to `request()`, which gets another 401, causing it to call `login()` again, getting stuck in infinite recursion. Instead of calling `login()`, we should probably make a "raw" login request instead of calling `login()` which also adds in all the version-retrying.

**Comment by srijeet0406** [comment]
I can take this one.
