### ISSUE TITLE
ag-grid tables export csv as undefined.csv

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#6176]
## This Bug Report affects these Traffic Control components:
- Traffic Portal

## Current behavior:
ag-grid tables export csv as undefined.csv by default - i.e. https://tp.domain.tld/#!/cdns/1/servers

## Expected behavior:
file name should reflect the content of the csv. i.e. servers.csv, users.csv, etc...

## Steps to reproduce:
Navigate to https://tp.domain.tld/#!/cdns/1/servers and More > Export CSV and observe the default file name is undefined.csv

**Comment by ocket8888** [comment]
Does this affect all/only AG-Grid tables, or does it also apply to some/all jQuery datatables?

**Comment by ocket8888** [comment]
In the case of AG-Grid tables, I think it's likely that [the `fileName` export options property](https://www.ag-grid.com/javascript-data-grid/csv-export/#csvexportparams) is being set explicitly to `undefined`, rather than truly not being defined. Or it's being set to a string coercion of a value that is `undefined` when it shouldn't be.

**Comment by mitchell852** [comment]
> Does this affect all/only AG-Grid tables, or does it also apply to some/all jQuery datatables?

sorry, not sure. didn't check them all.

**Comment by shamrickus** [comment]
I assume this is an issue with the ag-grid tables, without looking I'd guess the table name isn't being bound/referenced properly

**Comment by mitchell852** [comment]
> I assume this is an issue with the ag-grid tables, without looking I'd guess the table name isn't being bound/referenced properly

yeah, i think safe to say just the ag-grid tables
