### ISSUE TITLE
Traffic Stats should use TO API v3

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#6694]
## This Improvement request (usability, performance, tech debt, etc.) affects these Traffic Control components:

- Traffic Stats

## Current behavior:

Traffic Stats uses TO API v2.

## New behavior:

Traffic Stats should use TO API v3, since that is the current stable TO API version, and TO API v2 is being removed.

**Comment by mitchell852** [comment]
@rawlinp can you put an effort level on this if you know it?

**Comment by rawlinp** [comment]
That means we can't remove API 2.x until 4.x is stabilized, but maybe we're ok with that? Either way, for TS, this is a really low effort change.

**Comment by jhowar201** [comment]
Will take a look at this.

**Comment by ocket8888** [comment]
If we put this on the 6.2.0 milestone instead of 7.0.0 then we can still get rid of APIv2 at the same time as stabilizing v4. We'd need to wait for 7.0.1, minimum, to update TS to using APIv4, though, since it doesn't properly fall back. Unless we don't care about breaking Stats deployments across the major version boundary a la TP.
