### ISSUE TITLE
Delivery Service and Traffic Router can't loadbalance traffic between cache servers

### ISSUE THREAD

**Issue by ThanhLam2396** [apache/trafficcontrol#6902]
## This Bug Report affects these Traffic Control components
- Delivery Service
- Traffic Router
- Cache Server
## Current behavior:
We have a large cache with about 100 servers. And Delivery Services to deliver content using the https protocol (and HTTP Content Routing). However, when a large amount of traffic is poured in, we have noticed that the traffic between the cache servers chosen by the traffic router as a content delivery target is not evenly distributed. Only about 15-20 cache servers receive a lot of traffic, the rest are very little. This degrades the performance of our CDN cluster and causes overload for the high-traffic servers and idles for the rest of the cache servers. We tried configuring with a maximum Initial Dispersion of 10, but this only addresses the balance between 10 servers. Can someone tell me what we need to do to balance the traffic between 100 servers like a simple round-robin that many other technologies use. Is this a bug or just a misunderstanding of the content delivery mechanism of traffic control? Thank you, looking forward to your help

**Comment by rawlinp** [comment]
This is not a bug. Traffic Router is not a load balancer -- it is a content router. If requests were simply routed to servers in a round-robin fashion, cache hit ratio would be terrible, because nearly every request for a piece of content would be made to a cold cache. For example, if you have 100 edge caches and TR round-robined requests to all of them in turn, the first 100 requests for a given piece of content would be cache misses. The CDN is designed to cache content as efficiently as possible, which is why it uses a concept known as Consistent Hashing (as opposed to round robin).

That said, if using HTTP-routed delivery services, you could in theory set your initial dispersion to 100. But that would mean every unique piece of content would be duplicated 100 times in each of your cachegroups. If the amount of storage is not enough to handle that amount of duplication, your caches will quickly "wrap around" and content will be constantly getting pushed out of cache, reducing cache efficiency. Plus, the first 100ish requests for that given piece of content would be cache misses altogether.
