### ISSUE TITLE
Can not running postinstall

### ISSUE THREAD

**Issue by thang86** [apache/trafficcontrol#6986]
When I follow install traffic OPs
[root@localhost ~]# /opt/traffic_ops/install/bin/postinstall
postinstall requires the postgres user to have superuser access to postgresql. Aborting.

but when i bypass check 
root@localhost ~]# su - postgres psql -w -c 'show is_superuser'
su: invalid option -- 'w'
Try 'su --help' for more information.

and i test 
[postgres@localhost ~]$  psql -w -c 'show is_superuser'
psql: error: fe_sendauth: no password supplied

What problem 

OS Rocky Linux

**Comment by ocket8888** [comment]
You are using `su` improperly, consult [`man su`](https://man7.org/linux/man-pages/man1/su.1.html).

Your PostgreSQL setup does not allow for the postgres user to authenticate without a password, consult [the PostgreSQL documentation](postgresql.org/docs/).

For troubleshooting help, please [join our Slack channel(s) on the ASF Slack workspace](https://s.apache.org/tc-slack-request) instead of opening issues.

**Comment by thang86** [comment]
This command inculde postintall script 
# make sure installed with proper permissions
umask 022

if [[ ! $(su - postgres psql -w -c 'show is_superuser' </dev/null 2>/dev/null) =~ 'on' ]]; then
        echo >&2 "postinstall requires the postgres user to have superuser access to postgresql. Aborting."
        exit 1
fi

and document ats for traffic ops have command : 
su - postgres -c '/usr/pgsql-13/bin/initdb -A md5 -W' #-W forces the user to provide a superuser (postgres) password

This conflict command and script included /opt/traffic_ops/install/bin/postinstall

**Comment by ocket8888** [comment]
For troubleshooting help, please [join our Slack channel(s) on the ASF Slack workspace](https://s.apache.org/tc-slack-request).
