### ISSUE TITLE
Traffic Portal v1 - Quick Search does not work for second/layered profiles

### ISSUE THREAD

**Issue by TaylorCFrey** [apache/trafficcontrol#7052]
## This Bug Report affects these Traffic Control components:

- Traffic Portal

## Current behavior:

Open the server table in Traffic Portal. At the top of the page is the "Quick search" input field. The quick search does not filter / show servers if the input is the second/layered profile.

## Expected behavior:

If a server were to have "PRIMARY_PROFILE" assigned as the first profile, it will be filtered and show correctly, as expected. Additionally if you were to create and add a "SECONDARY_PROFILE" to the same server(s) the Quick search would display said server(s).

## Steps to reproduce:

Create a server (or use existing). Assign a profile ("PRIMARY_PROFILE" for example). This should be the first and only profile assigned to the server. You can verify that Quick search on the Configure->Servers page works for said profile.

Then create and/or add another profile (say "SECONDARY_PROFILE"). Then add this profile to the same server such that it has both PRIMARY and SECONDARY profiles assigned. Go to the Configure->Servers page and attempt to Quick Search on "SECONDARY_PROFILE" and the list will be empty

**Comment by ocket8888** [comment]
The simplest fix would be to update the display value to include all Profile names, probably separated by `, `. Then a filter on the table would check all of the profiles because the cell value is composed of all profiles.

In TPv2 we could make a custom filter for Profiles such that you can include and exclude specific names even if they are substrings of one another. For example, if using the solution above you filter for "Profile contains 'foo' and doesn't contain 'bar'" you would get as a match servers with profile 'foo' but not servers with profile 'foobar', whereas I really only meant to exclude the profile name that is exactly 'bar'.
