### ISSUE TITLE
problem with files download with macos

### ISSUE THREAD

**Issue by emiremron** [apache/trafficcontrol#7856]
We encountered a strange problem.
When users (Clients) use the following two methods to download files, at the end of the download, the speed suddenly becomes zero and the file is not downloaded until the end. And I don't see any errors in the Edge logs. I feel that it is not compatible with a series of download managers. And have you ever encountered this problem, and do you know what the problem is?
1-macos
2-eagle download manager
we also test with both macos 14: progressive downloader and eagle download manager.

**Comment by ocket8888** [comment]
Traffic Portal does not support "eagle download manager" as a browser - officially we support the latest Chrome and Firefox only.

Is this some kind of Microsoft Edge plugin? What files are you attempting to download?

**Comment by emiremron** [comment]
Dear sir/madam
the eagle is a download manager.
I want to be more precise, for example, we have this problem in downloading
manager called folx on MacBooks. The files are not downloaded completely.
this report of a user:
We use folx download manager. But unfortunately, in some cases, we
encounter problems and the file is not downloaded until the end (usually it
stops between 90 to 99% and fails.). But when we download the same file
using other download managers or even the browser, it is completely
downloaded. Most of the times when we use cdn links. My question is whether
the method used by folx is different from other download managers and how
exactly should I check this. Even if I want to follow up with CDN
providers, what exactly should they check and solve?
and also we check some download manager, And we saw that the same problem
exists.

[image: image.png]

**Comment by ocket8888** [comment]
What files are you downloading?

**Comment by emiremron** [comment]
[image: image.png]
.I have a test server as a download host and a server as a Mac OS client,
and I tested almost the following contents to download, they all had the
same problem in a strange way. And this problem does not exist when
downloading from Origin!
Download manager software on Mac:
Progressive Downloader
folx
Tested contents:
image (png, jpg)
videos (mp4,....)
compressed files rar, zip
exe

**Comment by ocket8888** [comment]
You keep adding the words "`[image: image.png]`" which indicates that you are intending to add some kind of image to your posts - but I assure you they are not there.

It sounds like this is a request for help troubleshooting a setup, in which case I'm going to direct you to the [users@trafficcontrol.apache.org](mailto:users@trafficcontrol.apache.org?subject=Help Setting Up a Demo Environment) mailing list and [our Slack channel](https://s.apache.org/tc-slack-request) for that. Consider also using the pre-built demo environment, ["CDN-in-a-Box"](https://traffic-control-cdn.readthedocs.io/en/latest/admin/quick_howto/ciab.html) rather than attempting to set up your own.
