### ISSUE TITLE
[TC-385] IPv6 Origin Configuration Not Allowed

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#899]
<p>IPv6 origins need to be configured using brackets if using the IP (such as <a href="http://[fec0::250:56ff:fea9:172" class="external-link" rel="nofollow">http://[fec0::250:56ff:fea9:172</a>]), but Traffic Ops rejects it with error:</p>

<p><span class="error">&#91;fec0 is not a valid org server name (rfc1123) or :250:56ff:fea9:172&#93;</span> is not a valid port</p>

Author: Zhilin Huang
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-385">https://issues.apache.org/jira/browse/TC-385</a>

**Comment by dneuman64** [comment]
I don't believe this will be backported to be included in 2.1.  Moving to 2.2

**Comment by rawlinp** [comment]
As far as I know, ipv6 addresses should be rejected, because the validation of that field has always been that it is a valid fqdn/hostname per rfc1123. It's just a coincidence that IPv4 addresses also happen to be valid hostnames.

Since we never explicitly disallowed ipv4 addresses in that field, it has become practice to use them in certain cases and have hence been supported throughout Traffic Ops. If we wanted to start allowing ipv6 addresses in this field, we'd have to verify and fix anywhere this field is used to make sure it's actually supported.

So, I don't believe this is a bug but really a feature request which should be prioritized as such.

**Comment by mitchell852** [comment]
this seems somewhat related to #890 as if we're going to allow ip addresses for origins then apparently dest_ip needs to be used instead of dest_domain in parent.config and cache.config

**Comment by mitchell852** [comment]
@rawlinp - do u think this can be closed?

**Comment by rawlinp** [comment]
@mitchell852 I think that depends on how much desire there still is to actually allow IPv6 addresses in the `orgServerFqdn` field, which doesn't seem like much since this ticket was created. Also, the PR #159 that addresses the related issue #890 hasn't seen any activity in a long time.

**Comment by dneuman64** [comment]
+1, I think the orgServerFQDN field should only contain FQDNs.  I am going to close this issue, if you feel like it needs to be re-opened then please re-open.
