### ISSUE TITLE
[TC-69] Upgrade Tomcat Version for Traffic Router

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#925]
<p>Traffic Router currently uses tomcat 6.0.33, this version of Tomcat will be EOL soon, so we need to update to a newer (latest?) version.</p>

Author: David Neuman
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-69">https://issues.apache.org/jira/browse/TC-69</a>
Found Version: 2.1.0

**Comment by mitchell852** [comment]
@ajschmidt is looking at this (CDN-393)

**Comment by ajschmidt** [comment]
https://github.com/apache/incubator-trafficcontrol/pull/2331

**Comment by ajschmidt** [comment]
Hello,
I have submitted a PR (#2331) for this major upgrade. We are looking to
make this part of the TC 3.0 release because it is a large change and the
update will automatically uninstall older versions of Traffic Router. The
update will upgrade the Tomcat to 8.5.28+ and will require Java 8, CentOs 7
and the installation of OpenSSL, Tomcat Native and APR. Most of this will
be taken care of by the RPM. Here is the migration documentation :

Traffic Router - Migrating to 3.0 <#contents>

Contents

   - Traffic Router - Migrating to 3.0 <#traffic-router-migrating-to-3-0>
      - Release Notes v3.0 <#release-notes-v3-0>
      - System Requirements <#system-requirements>
      - Upgrade Procedure <#upgrade-procedure>
      - Development Environment Upgrade <#development-environment-upgrade>

Release Notes v3.0 <#contents>

   - Replaced custom Java SNI implementation with a native implementation
   using tomcat-native, apr (Apache Portable Runtime) and OpenSSL This should
   significantly improve the performance of routing ‘https’ delivery services.
   - Upgraded to Tomcat 8.5.30
   - Separated the Traffic Router installation from the Tomcat deployment
   and created a new ‘tomcat’ package for installing Tomcat. Traffic Router
   and Tomcat can now be upgraded independently
   - Converted Traffic Router to a ‘systemd’ service
   - Modified the development test and dev deployment processes to be more
   consistent with production

System Requirements <#contents>

   - Centos 7.2
   - OpenSSL >= 1.0.2 installed
   - JDK >= 8.0 installed or available in Yum repository
   - APR (Apache Portable Runtime) >= 1.4.8-3 installed or available in Yum
   repository
   - Tomcat Native >= 1.2.16 installed or available in Yum repository
   - tomcat >= 8.5-28 installed or available in Yum repository (This
   package is created automatically by the Traffic Router build process)

Upgrade Procedure <#contents>

   - upload tomcat.rpm to a Yum repository
   - update the traffic_router package
   - restore property files

Upload tomcat.rpm

The ‘tomcat’ package gets created when you build Traffic Router. You must
either add it to the yum repo where you keep all of the Traffic Control
packages, or manually copy it to the servers where you will be installing
Traffic Router and run yum install [path to package] It is preferable that
you add it to your Yum repository because then it will be installed
automatically when you perform the Traffic Router update.
Update the traffic_router Package

If openssl, apr, tomcat-native, jdk and tomcat_tr packages are all in an
available repository then you just need to run: yum update traffic_router.
This will first cause the apr, tomcat-native, jdk and tomcat packages to be
installed. When the ‘tomcat’ package runs, it will cause any older versions
of traffic_router or tomcat to be uninstalled. This is because the previous
versions of the traffic_router package included an untracked installation
of tomcat.
Restore Property Files

Replace the Traffic Router properties files with the correct ones for the
CDN. The properties files from the previous install can be found at:
/opt/traffic_router/conf/traffic_ops.properties.rpmsaved &
traffic_monitor.properties.rpmsaved.
Development Environment Upgrade <#contents>

If you already have a development environment set up for the previous
version of Traffic Router, then you will need to get and install these
libraries on your workstation: openssl, apr and tomcat-native. Also,
whenever you run either ‘mvn clean verify’ or ‘TrafficRouterStart’ you will
need to pass a command line parameter telling Java where to look for the
‘tomcat-native’ libraries:mvn clean verify -Djava.library.path=[tomcat
native library path on your box]java -Djava.library.path=[tomcat native
library path on your box] TrafficRouterStart

**Comment by limited** [comment]
Very exciting Andy!  

* Any idea on the HTTPS performance improvements from this upgrade?
* Requirements say Centos 7.2. Hoping 7.2 is just the minimum and it can be any version greater?
* Does Oracle vs OpenJDK matter? Will either one work?
* Is there any reason not to automatically use the previous to and tm properties files after the upgrade?
* Are there any changes to the APIs (CrConfig, Steering, Federation, health.json) that would cause versioning issues with TO. Could we use the TR3 with a 2.2 or 2.3 Traffic Ops/Traffic Monitor

**Comment by ajschmidt** [comment]
1. We are still planning the performance testing. Nothing on that yet. 
2. You are right.  It is Centos 7.2 +. 
3. I did do some testing with OpenJDK and it seemed to be working fine, but nothing formal.  The main thing is that the RPMs have a dependency on a package:  jdk >= 1.8
4. You are right. My documentation is out of date there. The install does not replace any of the files on the /opt/traffic_router/conf directory. Your previous property files should be safe to use. 
5. In its current state there are no API changes. It has been tested with 2.2 and 2.3. However, I plan to keep it up to date with the Traffic Control master until it gets released so if any API changes come in that way we will have to decide what to support at that time.

**Comment by mitchell852** [comment]
the applicable PR was merged
