### ISSUE TITLE
[TC-467] Delivery-service tenancy based access control - DNSSEC and SSL Keys

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#939]
<p>We have recently added "tenancy" to the project. <br/>
With tenancy, every resource have a tenant, where resource can be a delivery-service, a server (future) and even a user.<br/>
We are now starting to enforce access-control based on the resource tenancy. A user can manage a resource only if the resource is under the user tenancy.</p>

<p>This JIRA deals with another step of "delivery-service as a resource" - enforcing access control on the management of ssl keys and DNSSEC, according to their Delivery service.<br/>
We still need to finalize the specification of this access control, and it would not be included in the first phase of tenancy introduction, assuming that the application hide from the user the ability to deal with entries relating to DSes which are not under his tenancy.</p>

Author: Nir Sopher
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-467">https://issues.apache.org/jira/browse/TC-467</a>

**Comment by mitchell852** [comment]
@nir-sopher - do you think this issue is still relevant? i believe you cannot manipulate ssl keys for a ds outside your tenancy nor do i think you can affect dnssec keys at the ds-level.

**Comment by rawlinp** [comment]
I believe the per-DS APIs for manipulating sslkeys, URI signing keys, and URL sig keys are all covered by tenancy checks, but the CDN-specific APIs that get all sslkeys or dnsseckeys are not covered by tenancy checks (since in essence those APIs are meant to provide _all_ of those things within a CDN). They do require admin privileges, however, so I'm not sure tenancy checks should be required for those anyways.

Feel free to re-open this issue if anyone disagrees.
