### ISSUE TITLE
[TC-285] When deleting delivery services associated parameters should be deleted

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#963]
<p>All associated parameters like certificates, plugins, and delivery service profiles should be deleted.</p>

Author: Derek Gelinas
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-285">https://issues.apache.org/jira/browse/TC-285</a>

**Comment by mitchell852** [comment]
@dg4prez - can you provide some more info or examples? what kind of ds plugins are you referring to?

**Comment by dg4prez** [comment]
I'm not sure about plugins or why that was mentioned, but the intent was anything specific to that delivery service like certificate files, profiles, origins only assigned to that DS, etc should be cleared.

**Comment by mitchell852** [comment]
> the intent was anything specific to that delivery service like certificate files, profiles, origins only assigned to that DS, etc should be cleared.

i'll check but pretty sure certs and origins are removed when a ds is deleted. profiles probably not because in theory ds profiles can be used across ds's even though they probably are not.

**Comment by rob05c** [comment]
Certs are removed on the next Snapshot.

Anything deleted that's used outside Snapshots (directly by TR, ORT, etc) _must_ not be deleted before the next Snapshot.

Even then, there's a bit of a race, because it takes time for the Snapshot to propagate. We should really delete stuff only after knowing the Snapshot has propagated to everything. But we don't have that data yet (it's part of the Kill the Chicken plan).

**Comment by mitchell852** [comment]
tbh i _think_ most everything directly linked to a ds is deleted now when a ds is deleted. except for ds profiles because profiles were designed for use with multiple things.

**Comment by dg4prez** [comment]
This can be closed
